<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.2 setup script
 * Date: Tue, 12 May 2020 19:05:53 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['only_db'] = '';
$cfg['Servers'][$i]['hide_db'] = '';

/* End of servers configuration */

$cfg['Console']['Mode'] = 'collapse';
$cfg['blowfish_secret'] = '5mS04N0h0=xAMW6sq=9cm,QzspT.iKE,';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
?>